name: Build and Publish Java

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'java/build.gradle'

jobs:
  build_and_publish_java:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') || startsWith(github.event.head_commit.message, 'release:')
    defaults:
      run:
        working-directory: './java'

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
      GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8.0.392+8'

      - name: Build
        run: |
          echo "Building Java project"
          chmod +x ./gradlew
          ./gradlew build

      - name: Publish to Maven Repository
        run: |
          echo "centralUsername=${CENTRAL_USERNAME}" >> gradle.properties
          echo "centralPassword=${CENTRAL_PASSWORD}" >> gradle.properties
          echo "gpgPublicKey=${GPG_PUBLIC_KEY}" >>  gradle.properties
          echo "gpgSecretKey=${GPG_SECRET_KEY}" >>  gradle.properties
          echo "gpgPassphrase=${GPG_PASSPHRASE}" >> gradle.properties
          echo "githubToken=${GITHUB_TOKEN}" >> gradle.properties
          echo "Publishing to Maven repository"
          ./gradlew publish
          ./gradlew jreleaserFullRelease
        env:
          GRADLE_USER_HOME: ./gradle
